version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "6009:6009"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=your_database_url

  frontend:
    build:
      context: ./frontend
    ports:
      - "6010:6010"
    volumes:
      - ./frontend:/app